import { existsSync } from 'fs';
import { resolve } from 'path';

// Expression to check if into input-file are some number, space or symbol
const nonMatchEncExp = RegExp("[\\[\\]$&+,:;=¿¡?@#|'<>.^*()%!-]|\\ |\\d");
// Expression to check if input-file has some non decodable pattern
const nonMatchDecExp = RegExp("[a-zA-Z][a-zA-Z]|^[A-Za-z]|[\\[\\]$&+,:;=¿¡?@#|'<>.^*()%!-]|\\ ");

/**
 * Check if a file exists, by using resolve and existsSync methods, from path and fs modules
 * respectively.
 * @param filepath
 * @returns The value by evaluate if the file exists.
 * @see resolve {@link resolve}
 * @see existsSync {@link existsSync}
 */
export const isValidFilePath = (filepath: unknown): boolean =>
  existsSync(resolve(filepath as string));

/**
 * Check if the given file data has the right format to encode.
 * @param data  Text result from read the input file.
 */
export const hasCodableFormat = (data: string): boolean => !nonMatchEncExp.test(data);

/**
 * Check if the given file data has the right format to decode.
 * @param data  Text result from read the input file.
 */
export const hasDecodableFormat = (data: string): boolean => !nonMatchDecExp.test(data);

/**
 * Parse data as an array where each line represents a value from that array
 * @param data
 * @returns arrayData
 */
export const splitDataByLineBreak = (data: string): string[] => data.split(/\r?\n/) ?? [data];

/**
 * Join each position of the arrayFromData using a linebreak as separator.
 * @param arrayData  Data generated by encode|decode action
 * @returns data  To returns to it original shape
 */
export const joinDataByLineBreak = (arrayData: string[]): string => arrayData.join('\r\n');
